#lang pollen
◊define-meta[type]{Anotace k textu}
◊define-meta[title]{BOURGOIS, Philippe. In Search of Respect: Selling Crack in El Barrio. Cambridge University Press, 2002.}
◊define-meta[title-short]{White: Tropika diskurzu (2010)}

Philippe Bourgois se ve své etnografii zaměřuje na pouliční kulturu marginalizovaných komunit v newyorské čtvrti Harlemu od druhé poloviny 80. let do poloviny 90. let. Jeho záměrem bylo zkoumat „politickou ekonomii“ pouliční kultury, ekonomickou marginalizaci a rasovou segregaci hispánců a afroameričanů. Zajímal se o to, jak si zdejší obyvatelé§zajišťují živobytí v nelegální ekonomice, která tvořila hlavní zdroj příjmů pro velkou část obyvatel čtvrti. V oblasti zrovna rostla popularita cracku a později heroinu, a drogový obchod poskytoval chudým obyvatelům lepší příjmy než legální, daněné práce. Jeho hlavními informátory byli portorikánští podnikatelé a zaměstnanci jednoho crackového podniku ve čtvrti El Barrio.

V úvodu se autor svěřuje čtenáři s dilematy, které pociťoval při publikaci etnografie. Obával se rizika, když ukáže utrpení a násilí života bez cenzury a přikrášlení, bude na jedné straně obviňován akademickou obcí z negativní stereotypizace chudých, na druhé straně poskytne materiál rasistům a klasistům pro tuto negativní stereotypizaci. Bourgois se obhajuje, že ukazuje chudobu v pravdivém světle, a jak říká, lidské utrpení je vždy ošklivé. Kritizuje přitom pokrytectví kabinetních, dekonstrukcionistických akademiků, kteří si chudobu idealizují a představují si marginalizované komunity jako produkty socio-ekonomických sil bez schopnosti jednat. Bourgois uznává působení strukturálních sil, ale zároveň i schopnost lidí se těmto vnějším tlakům přizpůsobovat a jednat v nich.

◊heading{Vstup do terénu}

V první kapitole se Bourgois vyrovnává s různými aspekty vstupu do terénu. Problémy se v zásadě otáčejí kolem rozdílů v barvě pleti a v kulturním kapitálu. Bourgois je bílý muž pocházející z elitního akademického prostředí, které oceňuje jiné druhy jednání, než členové pouliční kultury tmavé barvy pleti. Autor se snaží v této komunitě najít společný jazyk a osvojit si kulturní praxe, které mu zajistí uznání v komunitě (odsud „searching for respect“). V průběhu tohoto procesu se dopouští přešlapů, nedorozumění a ◊em{faux pas} – například když šéfovi crackového podniku Rayovi, který je jeho klíčovým gatekeeperem, dá k přečtení novinový článek, čímž odhalí jeho negramotnost a zesměšní ho před družinou jeho následovníků a zaměstnanců. Rozdíl v kulturních kapitálech později vedl k tomu, že se jej Ray snažil využít k vzestupu do střední třídy, ve které se však nikdy nedokázal zorientovat.

Bourgois byl dlouho svými informátory podezříván z toho, že je tajným policistou, a dlouho trvalo, než si u nich vybudoval dostatečnou důvěru a než si ho dokonce oblíbili. Po určité době se mu svěřili, že ho považovali za homosexuála (pouliční kultura byla homofobní), přičemž si uvědomí, že na začátku terénního výzkumu misinterpretoval některé náznaky, kterými mu to dávali ostatní najevo. Jiné neporozumění vyvstalo ohledně představ o reciprocitě. Bourgois se obával, že místní nelibě ponesou, že je využívá ke své akademické kariéře, ačkoliv jeho „ušlechtilým“ dlouhodobým záměrem byl příspěvek k porozumění sociální marginalizaci, čímž se zamýšlel odplatit komunitě. Místním však připadal kariérní oportunismus naprosto srozumitelný a naopak k představě, že by jim vydání knihy mohlo být nějak užitečné, se stavěli s krajní nedůvěrou. To bylo v souladu s jejich představou, že cílem každého rozumného člověka je vydělat spoustu peněz.

Druhou zásadní překážkou při vstupu do komunity byl rasismus a rozdíl v barvě pleti. Na místě prakticky fungoval nepsaný apartheid. Bílá a černá sousedství byly od sebe odděleny a lidé toto rozdělení dodržovali. Východní Harlem byl téměř výhradně obydlen chudými afroameričany a hispánci a běloši ze střední třídy sem nechodili ze strachu, že budou přepadeni a oloupeni. Naopak místní obyvatelé nechodili ven, protože se ve světě bílé střední třídy neuměli orientovat, neměli odpovídající kulturní kapitál, nevyznali se v byrokracii, neměli uznání, zkrátka mimo svou komunitu nebyli nikým. Nejen že tuto bariéru lidé samovolně udržovali, tato bariéra byla i prakticky vynucována policií: například když byl antropolog při jednom z mnohých zadržení policí považován za drogově závislého, vyptávali se ho policisté, proč si nejde koupit drogy do bílé čtvrti. Když se tedy Bourgois rozhodl vydat do východního Harlemu, porušil tím symbolickou hranici. Proto byl buď považován za tajného policistu, nebo za bílého drogově závislého, který si sem ze sousední čtvrtě přišel opatřit drogy. Z toho důvodu ho policisté několikrát zadrželi, nebo se ho alespoň podiveně vyptávali, co tam dělá. Nikoho nenapadlo, že běloch může být místní rezident.
