#lang pollen

◊title{K antropologické teorii hodnoty: falešná mince našich snů}

◊heading{Tři způsoby, jak mluvit o hodnotě}

Když člověk čte hodně antropologických textů, těžko unikne dojmu, že teorie hodnoty jsou poslední dobou v módě. Rozhodně lze často narazit na zmínky o „hodnotě“ a „teoriích hodnoty“, obvykle nadhozené způsobem, který jakoby naznačoval, že za nimi stojí množství pravděpodobně velmi komplikované literatury. Když se však pokusíme tuto literaturu dohledat, rychle narazíme na problém. Je totiž velmi obtížné nalézt systematickou„teorii hodnoty“ v jakékoliv literatuře z poslední doby, a zpravidla se ukáže, že je velmi težké dovtípit se, na kterou sadu teorií daný autor navazuje, pokud vůbec. Člověk by skoro pojal podezření, že to je ta samotná nejednoznačnost pojmu, která jej činí tak atraktivním.

◊blockquote{V této kapitole bych se rád pokusil nabídnout některá vysvětlení, jak k této situaci došlo. Podle mého názoru to souvisí s tím, že antropologie se zasekla v jakémsi teoretickém limbu. Nikdy totiž nevyřešila teoretická dilemata z doby zhruba před dvaceti lety; spíš jakoby nad nimi pokrčila rameny. Panuje všeobecná nálada, že teorie hodnoty by byla právě tím, co by je vyřešilo, jenže taková teorie nikdy nevznikla; nejspíš proto se stalo zvykem akademiků předstírat jakoby existovala.}

Bude snazší pochopit, proč by teorie hodnoty měla být tak slibná, když se podíváme na způsob, jak se slovo „hodnota“ používalo v sociálních vědách v minulosti. Existují v podstatě tři velké proudy myšlení, které se sbíhají v současném pojmu. Jsou to:

◊numbered-list{
◊item{„hodnoty“ v sociologickém smyslu: pojetí toho, co je dobré, patřičné a žádoucí v lidském životě}
◊item{„hodnota“ v ekonomickém smyslu: stupeň toho, jak moc jsou předměty žádoucí, jehož měřítkem je, kolika jsou ostatní osoby ochotné vzdát se, aby jej získaly}
◊item{„hodnota“ v lingvistickém smyslu, která má původ ve strukturální lingvistice Ferdinanda de Saussura (1966) a jinými slovy by se dala nazvat jako „významný rozdíl“}
}

Když antropologové mluví o „hodnotě“ – zejména když píšou „hodnota“ v singuláru tam, kde by někdo před dvaceti lety psal o „hodnotách“ v plurálu – alespoň tím naznačují, že když označujeme tyto tři věci stejným slovem, není to náhoda. Že jde nakonec o odlesky téže věci. Když se nad tím ale zamyslíme, je to poněkud vyzývavá představa. Znamenalo by to například, že když mluvíme o „významu“ slova a o „smyslu života“, nejde o zásadně odlišné věci, a že obě mají něco společného s prodejní cenou ledničky. Když to řekneme takto, vyvolává to samozřejmě nesouhlas. Skeptik by namítl: možná mají něco společného, ale kdyby to tak bylo, tak by „to“ společné bylo tak abstraktní a neurčité, že by nemělo smysl na to poukazovat. V tom případě nejednoznačnost opravdu ◊em{je} cílem. To si však nemyslím. Když se totiž podíváme na historie antropologického uvažování o každém z výše uvedených druhů hodnoty, zjistíme, že téměř pokaždé, když se teoretici pokoušeli vymyslet koherentní teorii jednoho z nich, strašlivě selhali kvůli tomu, že nevzali dostatečně v úvahu ty ostatní.

Dovolte mi stručně načrtnout tyto historie, jednu po druhé:

◊subheading{Hodnotový projekt Clyda Kluckhohna}

Teoretická analýza „hodnot“ a „hodnotových systémů“ je povětšinou omezena na filosofii (kde se nazývá „axiologií“) a sociologii (kde je tím, čeho je člověk prost, když je „bezhodnotový“). Neznamená to, že by antropologové nikdy pojem nepoužívali. Mohli bychom vybrat antropologické dílo z téměř kterékoliv doby a kdybychom jím listovali dostatečně dlouho, téměř jistě bychom narazili na jednu nebo dvě zmínky „hodnot“. Antropologové se je však zřídkakdy pokusili definovat, natož je analyzovat jako součást antropologické teorie. Jedinou velkou výjimkou byl Clyde Kluckhohn, který na přelomu 40. a 50. let spolu s týmem spřízněných akademiků z Harvardu vyvinul významné úsilí umístit problém hodnot do středu antropologie. Kluckhohnovým projektem bylo vlastně redefinovat antropologii samotnou jako komparativní studium hodnot.

Dnes se na tento projekt vzpomíná především díky tomu, že se mu podařilo se dostat do Obecné teorie jednání od Talcotta Parsonse, která byla zamýšlená jako „mírová dohoda“ mezi sociologií, antropologií a psychologií, dělící studium lidského chování mezi tyto disciplíny. Psychologové měli zkoumat struktury individuální osobnosti, sociologové sociální vztahy a antropologové se měli zabývat, jak je obojí zprostředkováno kulturou, což v podstatě znamená, jak se hodnoty usazují v symbolech a významech. Hlavní Kluckhohnova antropologická práce se týkala Navahů, ale přišel také s myšlenkou komparativního výzkumu hodnot, která se zaměřovala na oblast Rimrock v Novém mexiku, rozdělenou mezi pět rozdílných komunit: Navahové, Zuniové, Mormoni, Texasané a Mexiko-američané. Domníval se, že její existence byla tím nejbližším k řízenému experimentu, jak se lze jen v antropologii dostat; poskytovala příležitost vidět, jak se pět skupin s podstatně odlišnými hodnotovými systémy přizpůsobilo stejnému prostředí. Do terénu vyslal pět studentů, jednoho do každé komunity (ve skutečnosti se do studie v Rimrocku nějakým způsobem zapojilo značné množství amerických antropologů následující generace), zatímco sám zůstal v Harvardu, kde pořádal semináře o hodnotách a vypracovával řady návrhů, které usilovaly o definici analytických pojmů.

Co jsou tedy přesně hodnoty? Kluckhohn neustále piloval své definice. Ústředním předpokladem však bylo, že hodnoty jsou „představy žádoucího“ – představy, které nějakým způsobem ovlivňují, jak si lidé volí mezi různými možnými cestami jednání. Klíčový pojem tu je „žádoucí“. Neoznačuje jednoduše to, co lidé skutečně chtějí – ti v praxi chtějí všemožné věci. Hodnoty jsou představy toho, co by lidé ◊em{měli} chtít. Jsou to kritéria, podle kterých lidé usuzují, které touhy jsou legitimní a žádoucí a které ne. Pokud tedy nejsou hodnoty představami o smyslu života, pak jsou alespoň o představami, co může člověk od života oprávněně požadovat. Problém však přichází z druhou částí definice: Kluckhohn také trval na tom, že nejde jen o abstraktní životní filosofie, ale o myšlenky, které mají přímý účinek na skutečné chování lidí. Potíž byla v tom, jak určit tento vliv.

Samozřejmě pokud mluvíme o hodnotách v tradičním smyslu, není to tak složité. Myslím tím v tom smyslu, kdybychom řekli například, že Navahové v Rimrocku si vysoce váží něčeho, čemu říkají „harmonie“, nebo Texané něčeho, čemu říkají „úspěch“. „Analýza hodnot“ obvykle znamená identifikovat tyto pojmy, interpretovat je, přijít na to, co přesně „harmonie“ nebo „úspěch“ znamená pro danou komunitu, a umístit je do širšího kulturního kontextu. Problém však je, že tyto pojmy jsou často velmi specifické. Kluckhohna zajímala systematická ◊em{komparace} hodnot.

Aby srovnal tyto představy, musel Kluckhohn se svými studenty nakonec vytvořit druhou, méně abstraktní úroveň, kterou nazval „hodnotové orientace“. Byly to „předpoklady o cílech a účelech lidské existence,“ o povaze poznání, „o tom, co lidé mají právo očekávat od druhých nebo od bohů, o tom, co konstituuje naplnění a frustraci.“ Jinými slovy, hodnotové orientace mísily představy o žádoucím s předpoklady o povaze světa, ve kterém člověk jedná. Dalším krokem bylo sestavit seznam základních existenciálních otázek, na které nejspíš musela mít každá kultura nějakou odpověď: jsou lidské bytosti dobré nebo zlé? Měl by jejich vztah k přírodě být založen na rovnováze, ovládnutí nebo zotročení? Měla by základní loajalita člověka být směřována k sobě, k větší skupině, nebo k ostatním jednotlivcům? Kluckhohn takový seznam sestavil, ale se svými studenty zjistil, že je velice obtížné posunout se od této extrémně jemné úrovně k světštějším záležitostem, jako proč lidé upřednostňují pěstovat brambory místo rýže nebo preferují sňatky se svými křížovými bratranci a sestřenicemi – tedy k těm každodenním záležitostem, kterými se antroplogové obvykle zajímají.

V tomto okamžiku příběh nabírá odstín tragedie. Skoro všichni, kteří se na Rimrockském výzkumu podíleli, měli pocit, že byl selhání; když terénní výzkumníci sepisovali závěry, zjistili, že je téměř nemožné nalézt společné pojmy. I přestože Kluckhohnovi žáci – zejména filosofka Edith Albert – nadále chrlili eseje oplývající vědeckou sebejistotou do  pozdních 50. a raných 60. let, Kluckhohn sám strávil poslední roky svého života sužován pocitem frustrace a neschopnosti dosáhnout průlomu, který by umožnil skutečné systematické komparativní studium hodnot a vztáhnul je odpovídajícím způsobem k jednání. O to více frustrující bylo vzhledem k tomu, že Kluckhohn považoval svůj projekt v mnoha ohledech za poslední zoufalé úsilí zachrnit americkou antropologii před něčím, co téměř všichni považovali za teoretickou stagnaci. Zatímco Britští antropologové vždycky považovali svou disciplínu za odnož sociologie, severoamerická škola založená Franzem Boasem čerpala z německé kulturní teorie a společnosti neporovnávala především jako způsoby organizace vztahů mezi lidmi, ale rovnocenně jako struktury myšlení a cítění. Předpokladem bylo, že v jádru kultury existují jisté klíčové vzorce, symboly či motivy, které držely vše pohromadě a nebylo je možné redukovat na čistou individuální psychologii; potíž spočívala v tom, je to definovat a jak se k nim dostat. Zbývá jen podivný, poněkud rozporuplný obrázek, protože to byla doba, kdy byla Boasovská antropologie na vrcholu svého populárního vlivu a své akademické autority, zahlcená penězmi za studené války, a kdy její knihy byly často čtené běžnými američany, ale zároveň byla zatížená pocitem intelektuálního bankrotu. Kluckhonovo úsilí předefinovat antropologii jako studium hodnot by se dalo považovat za poslední snahu spasit Boasovský projekt; dnes je považováno za jednu z mnohých slepých uliček. Konsensus mezi těmi, kteří se vůbec obtěžují mluvit o této epizodě, je však takový, že na projektu jako takovém nebylo nic špatného. Selhal spíš kvůli nedostupnosti adekvátní teorie struktury. Kluckhohn chtěl srovnátat systémy myšlenek, ale neměl žádný teoretický model toho, jak se myšlenky mají k sobě jako systémy. Posledních několik let svého života se čím dál více zajímal o půjčování si modelů z lingvistiky, ale tehdy dostupné nástroje na tento úkol zkrátka nestačily. Jeho kritici naznačují, že kdyby on nebo jeho projekt vydržel o několik let déle, dokud v pozdních 60. letech nevtrhly na scénu strukturalistické modely, vše mohlo dopadnout jinak.

Ať je to jakkoliv, projekt neměl žádné intelektuální nástupce. Neznamená to samozřejmě, že by antropologové už nemluvili o „hodnotách“. Některé regionální subdisciplíny jsou skutečně posedlé konkrétními hodnotami (zejména ty zabývající se regiony, které postrádají příliš propracované sociální struktury nebo rodové systémy): nejtypyčtěji antropologie středomoří, která se po většinu své historie zaměřovala na „čest.“ O „hodnotách“ obecně však není nic. Platí to dokonce i pro vědce pracující v Kluckhohnově vlastní intelektuální tradici. Někteří z nejvlivnějších Amerických kulturních teoretiků 60. a 70. let – mám na mysli zejména Clifforda Geertze nebo Davida Schneidera – na ni různámi způsoby navázali, ale vydali se odlišnými směry.

Takhle to vypadá příliš mizerně. Navzdory veškeré sterilnosti v praxi je na Kluckhonově klíčové myšlence něco přitažlivého: to, co odlišuje kultury, nejsou jen jejich představy o tom, jaký je svět, ale pocity, co od něj můžou oprávněně požadovat. Jinými slovy, taková antropologie by byla komparativním studiem praktických filosofií života. Nejbližší paralelou v sociálních vědách byl pravděpodobně Weberův komparativní výzkum světových nábožrnství, který se mimo jiné zabýval vymezením konečného počtu možných způsobů myšlení o smyslu lidské existence a porozuměním implikací každé z nich pro sociální život. Je možné, že je dokonce načase jeho práci oživit: poslední dobou proběhly určité pokusy, například od Charlese Nuckollse, integrovat takovou analýzu hodnot s psychologickými přístupy v antropologii. Pro nynější účely je však podstatné, že první velké úsilí vybudovat antropologickou teorii hodnot téměř definitivně uvízlo na mělčině a že antropologický zájem o tyto problémy se s 60. léty začal vyvíjet dvěma opačnými směry: jeden, který se ohlížel za ekonomií, a druhý za lingvistikou.
